### ISSUE TITLE
Set Maximum value

### ISSUE THREAD

**Issue by stulincoln** [snuids/grafana-radar-panel#14]
Is there anyway to set a maximum value for the outside line? I am plotting a maturity rating out of 5 and since our current high score out of all the values is only 2.5 the maximum value is 2.5. I would like to manually set this.

**Comment by snuids** [comment]
The version 1.4.4 is supposed to handle that. Check the Autoscale parameter.

Cheers,

Arnaud

**Comment by stulincoln** [comment]
I downloaded the latest version with filename 341713c1 but do not see the option. If I look at the help in the panel itself it only appears to show change log up to V1.4.2

Tried clearing cache and restarting Grafana but still same situation.

Thanks

**Comment by stulincoln** [comment]
Sorry, filename 34713c1

**Comment by snuids** [comment]
That's strange. Can you check the grafana plugin.json file in the plugin directory. It should show 1.4.4 otherwise, something's wrong. How did you install the plugin. Manually or using the grafana plugin panel ?

**Comment by stulincoln** [comment]
Ok, I checked and the JSON file is correct. I even looked at src/editor.html and it has the scale options in there as well. Tried removing complete and re-adding but getting the same thing. I have around 15 plugins and this is the first time I have seen this. I download the winzip, unzip and drop the folder in the Plugins folder.

**Comment by stulincoln** [comment]
RESOLVED. I realized there was a sub directory of the plugins folder which had old folders in it. Once I removed and restarted it is now working and I see the options. Thanks for your assistance.
