### ISSUE TITLE
Radar panel fails to render with grafana-image-renderer plugin

### ISSUE THREAD

**Issue by GZRad** [snuids/grafana-radar-panel#28]
The image renderer always times out. the reason being that the code never calls this.renderingCompleted();
Add it at the end of the "onRender" handler to fix.

**Comment by snuids** [comment]
Did you try it locally ? If it is the case, I simply add the line blindly.

**Comment by GZRad** [comment]
Yes, I did. Line 207 of radargraph_ctrl.js


                }
                this.radar.data = this.data;
                this.radar.update();
              }
            }
            this.renderingCompleted();
          }

**Comment by snuids** [comment]
Done, We will have to wait for grafana to accept it. v1.5.1

**Comment by GZRad** [comment]
appreciated
