### ISSUE TITLE
Radar without values

### ISSUE THREAD

**Issue by edslopes** [snuids/grafana-radar-panel#5]
Hello. 
I'm new to Grafana, however I'm trying to create new plugins to learn. I tried to use this plugin, doing all the steps informed, but without success. Radar does not appear. My code is exactly the same, yet the values ​​do not appear. As if the graph had zero values.

![screencapture-192-168-103-117-3000-dashboard-new-1516021682333](https://user-images.githubusercontent.com/35455837/34943895-af7e9c22-f9e4-11e7-97a5-e2db206342d4.png)

**Comment by snuids** [comment]
@edslopes

I checked the panel with PostGreSQL, InfluxDB and Elastic Search. The panel requires at least one aggregation in order to create the axis.

Which database are you using ?

**Comment by edslopes** [comment]
I'm using PostgreSQL. When I give a grunt, "PSQL detected" appears, but appears returning value "0". I'm checking the bank to see if I can find the problem. I updated the bank, now nothing appears, nor the axis that appeared before.

**Comment by snuids** [comment]
You must use a select query as shown on the postresql paragraph of the project’s read me. Your select must return a metric, a value and a time. Use the $__time for the time and it should work. Use also the $__timefilter in your where clause.

Cheers,

**Comment by edslopes** [comment]
I'll do it that way you explained it to me. Appreciate your attention. 

cheers.

**Comment by edslopes** [comment]
@snuids

I would like to point out that, indeed, my bank is not actually generating the data correctly, so it did not work. I fixed the error by creating new data without a bank. Thank you so much. 

cheers.
